name: Build

on:
  workflow_dispatch:

jobs:
  build:
    if: ${{ vars.INTEGRATION_TESTS_BUCKET != '' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Build
        run: ./mvnw clean compile
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: artifacts
